name: learn-github-issue
run-name: ${{ github.actor }} Learn GitHub Issue
on:
  issue_comment:
    types: [created]
jobs:
  welcome:
    name: Welcome contributor
    runs-on: ubuntu
    permissions:
      issues: write
    steps:
      - name: Welcome contributor
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Thanks for opening this issue, I glad to here what you wants!`
            })
