name: learn-github-issue
run-name: ${{ github.actor }} Learn GitHub Issue
on:
  pr_comment:
    types: [created]
jobs:
  welcome:
    name: Welcome contributor
    runs-on: ubuntu
    steps:
      - name: Welcome contributor
        uses: actions/github-script@v3
        permissions:
          issue-requests: read, write
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Thanks for opening this issue, I glad to here what you wants!`
            })
