name: jami-store-requests-manager
run-name: New organization request from ${{ github.actor }}
on:
  issue_comment:
    types: [created, edited]
jobs:
  verify-csr:
    permissions:
      issues: write
    if: contains(github.event.issue.labels.*.name, 'new organization request') && startsWith(github.event.comment.body, '/csr')
    runs-on:  ubuntu-latest
    steps:
      - name: verify the CSR file is attached
        id: verify_attached_csr
        uses: actions/github-script@v6
        with:
          script: |
            const regex = /https:\/\/github\.com\/.*\/files\/.*/;
            const comment = ${{ toJSON(github.event.comment) }};
            console.log(comment.body)
            const attachements = comment.body.match(regex);
            return { attachements };
      - name: get-repo-base-name
        id: repo
        uses: actions/github-script@v6
        with:
          script: |
            const repo = "${{ github.repository }}"
            baseName = repo.split("/").at(-1);
            return { baseName };
      - name: ask to upload the CSR file
        if: steps.verify_attached_csr.outputs.result.attachements.length == 0
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.actor }} Please upload your CSR file to your comment.
      - name: comment-verification-in-progress
        if: steps.verify_attached_csr.outputs.result.attachements.length == 1
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            CSR file uploaded, verification in progress
      - name: add label to process the request
        if: steps.verify_attached_csr.outputs.result.attachements.length == 1
        uses: actions/github-script@v6
        with:
          script: |
            console.log(${{ steps.repo }});
            github.rest.issues.addLabels({
              issue_number: parseInt("${{ github.event.issue.number }}"),
              owner: "${{ github.repository_owner}}",
              repo: "${{ steps.repo.outputs.baseName }}",
              labels: ['csr verification in progress']
            })
      - name: request verify the csr
        id: request-verify-csr
        if: steps.verify_attached_csr.outputs.result.attachements.length == 1
        uses: actions/github-script@v6
        with:
          script: curl -s ${{ steps.verify_attached_csr.outputs.result[0] }} | tar -xz -O csr.pem | openssl req -noout -text
      - name: handle error
        if: steps.verify_attached_csr.outputs.result.length == 1 && contains(steps.request-verify-csr.outputs.result[0], 'OK') == false
        id: request-verify-csr-error
        run: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'CSR is invalid, Please retry'
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['invalid csr']
            })
      - name: handle success when requesting verify the csr
        if: endsWith(steps.request-verify-csr..result.outputs, 'OK') && steps.verify_attached_csr.outputs.result.attachements.length == 1
        run: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ github.actor}}, your certificate signing request is valid. Please wait for a store manager to process your request.'
          })
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['valid csr']
          })
          github.rest.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: 'invalid csr'
          })
      - name: remove label to process the request
        if: steps.verify_attached_csr.outputs.result.attachements.length == 1
        run: |
          github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'verification in progress'
            })
