name: jami-store-requests-manager
run-name: New organization request from ${{ github.actor }}
on:
  issue_comment:
    types: [created, edited]
jobs:
  verify-csr:
    if: contains(github.event.issue.labels.*.name, 'new organization request') && startsWith(github.event.comment.body, '/csr')
    runs-on:  ubuntu-latest
    steps:
      - name: verify the CSR file is attached
        id: verify_attached_csr
        uses: actions/github-script@v6
        with:
          script: |
            const context = ${{ toJson(github.context) }};
            const event = ${{ toJson(github.event) }}; 
            console.log(context);
            console.log(event);
            const regex = new RegExp(/^https:\/\/github\.com\/savoirfairelinux\/jami-plugins-store-requests\/files\/.*/);
            const comment = '${{ github.context.payload.comment.body }}'
            return comment.match(regex);
      - name: ask to upload the CSR file
        if: steps.verify_attached_csr.outputs.result.length == 0
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: ${{ github.repository_owner }},
              repo: ${{ github.repository }},
              body: 'Please upload the CSR file'
            })
            exit 1
      - name: add label to process the request
        if: steps.verify_attached_csr.outputs.result.length == 1
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'CSR file uploaded, verification in progress'
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['csr verification in progress']
            })
      - name: request verify the csr
        id: request-verify-csr
        if: steps.verify_attached_csr.outputs.result.length == 1
        uses: actions/github-script@v6
        with:
          script: curl -s ${{ steps.verify_attached_csr.outputs.result[0] }} | tar -xz -O csr.pem | openssl req -noout -text
      - name: handle error
        if: steps.verify_attached_csr.outputs.result.length == 1 && contains(steps.request-verify-csr.outputs.result[0], 'OK') == false
        id: request-verify-csr-error
        run: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'CSR is invalid, Please retry'
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['invalid csr']
            })
      - name: handle success when requesting verify the csr
        if: endsWith(steps.request-verify-csr.outputs, 'OK') && steps.verify_attached_csr.outputs.result.length == 1
        run: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ github.actor}}, your certificate signing request is valid. Please wait for a store manager to process your request.'
          })
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['valid csr']
          })
          github.rest.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: 'invalid csr'
          })
      - name: remove label to process the request
        if: steps.verify_attached_csr.outputs.result.length == 1
        run: |
          github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'verification in progress'
            })
